{% set name = "anaconda.enterprise.server.common.sdk" %}
{% set version = "0.4.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python>=3.8
    - setuptools
  run:
    - python>=3.8

about:
  home: https://github.com/Anaconda-Platform/anaconda-enterprise-server-common-sdk
  summary: "Anaconda Enterprise Server Common SDK"
  license: BSD
  license_file: LICENSE
